// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'load3': string;
  'load4': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
