// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'disabled': string;
  'fullModeToggle': string;
  'icons': string;
  'root': string;
  'settingsIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
