// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'btn': string;
  'green': string;
  'icon': string;
  'orange': string;
  'purple': string;
  'red': string;
  'root': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
