// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'inputWrapper': string;
  'resultList': string;
  'root': string;
  'search': string;
  'searchSvg': string;
  'title': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
