// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'arrowRightSvg': string;
  'blue': string;
  'green': string;
  'input': string;
  'inputWrapper': string;
  'loader': string;
  'notFound': string;
  'orange': string;
  'purple': string;
  'red': string;
  'resultList': string;
  'resultWrapper': string;
  'root': string;
  'search': string;
  'searchSvg': string;
  'title': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
