// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'citys': string;
  'icon': string;
  'root': string;
  'temp': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
